# Generated by Django 3.0.3 on 2020-03-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='content',
            name='price',
        ),
    ]
